name: manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest  # 修正: rus-on -> runs-on
    steps:                  # 修正: stpes -> steps かつ インデント調整
      - run: echo "${{ inputs.greeting }}"
